### ISSUE TITLE
Issues when install rtmidi2 via pip

### ISSUE THREAD

**Issue by frederico-betting** [gesellkammer/rtmidi2#4]
I'm trying to install the lib using pip but I'm getting an error. It's the same when installing from the pipeline.
Could someone help me with that? Tks

The versions:

_Python: 3.8.12_
_pip: 22.0.4_
_setuptools: 61.0.0_

This is the error I'm currently getting:

```shell
Collecting rtmidi2
  Downloading rtmidi2-1.1.0.tar.gz (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 KB 49.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      /tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py:100: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
        warnings.warn(msg, _ExperimentalProjectMetadata)
      configuration error: `project.license` must be valid exactly by one definition (2 matches found):
      
          - keys:
              'file': {type: string}
            required: ['file']
          - keys:
              'text': {type: string}
            required: ['text']
      
      DESCRIPTION:
          `Project license <https://www.python.org/dev/peps/pep-0621/#license>`_.
      
      GIVEN VALUE:
          "MIT"
      
      OFFENDING RULE: 'oneOf'
      
      DEFINITION:
          {
              "oneOf": [
                  {
                      "properties": {
                          "file": {
                              "type": "string",
                              "$$description": [
                                  "Relative path to the file (UTF-8) which contains the license for the",
                                  "project."
                              ]
                          }
                      },
                      "required": [
                          "file"
                      ]
                  },
                  {
                      "properties": {
                          "text": {
                              "type": "string",
                              "$$description": [
                                  "The license of the project whose meaning is that of the",
                                  "`License field from the core metadata",
                                  "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                              ]
                          }
                      },
                      "required": [
                          "text"
                      ]
                  }
              ]
          }
      ignored error: ValueError - invalid pyproject.toml config: `project.license`
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 1[77](https://github.com/sampler-box/sampler-box/runs/5695244298?check_suite_focus=true#step:5:77), in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 39, in <module>
          setup(
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 76, in setup
          _install_setup_requires(attrs)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 68, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/dist.py", line [83](https://github.com/sampler-box/sampler-box/runs/5695244298?check_suite_focus=true#step:5:83)6, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/config/pyprojecttoml.py", line 53, in apply_configuration
          return apply(dist, config, filepath)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 42, in apply
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-h7sy_t2x/overlay/lib/python3.8/site-packages/setuptools/config/_apply_pyprojecttoml.py", line [120](https://github.com/sampler-box/sampler-box/runs/5695244298?check_suite_focus=true#step:5:120), in _license
          _set_config(dist, "license", val["text"])
      TypeError: string indices must be integers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: ERROR: Action failed during dependency installation attempt with error: The process '/opt/hostedtoolcache/Python/3.8.12/x64/bin/python' failed with exit code 1
```

**Comment by frederico-betting** [comment]
It was not failing when using setuptools version 60.10.0.

**Comment by frederico-betting** [comment]
I think I found the issue. I submitted a PR to fix that.

https://github.com/gesellkammer/rtmidi2/pull/5
